# Generated by Django 5.0.6 on 2026-06-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='paddle_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
