# Generated by Django 5.0.6 on 2026-07-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_profile_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='paddle_subscription_id',
        ),
    ]
