"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.4']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-Party Libraries
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    
    # Django-Allauth Required Apps
    'django.contrib.sites',  # Required by django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # Google Provider

    # Local Apps
    'authentication',
    'workouts',
    'background_task',
    'social.apps.SocialConfig',
]

# Required for django.contrib.sites
SITE_ID = 1

ASGI_APPLICATION = 'config.asgi.application'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Top item for safe mobile handshakes
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # Allauth middleware for account management
    'allauth.account.middleware.AccountMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', # Required by django-allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Amman' # Local operational timeline

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
# 2. Absolute filesystem path where Django collects all assets for live production deployments
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 3. (Optional but highly recommended) Explicitly specify asset discovery priorities
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder', # Scans workouts/static/ automatically
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:3000",
    "http://localhost:3000",
]
CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = 'authentication.User'

# Custom Authentication Backends
AUTHENTICATION_BACKENDS = [
    'authentication.views.EmailOrUsernameModelBackend',  # Pointing to views prevents the early model-load crash
    'django.contrib.auth.backends.ModelBackend',

    # Allauth Specific Authentication Backend
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Django-Allauth Configurations & Account Reconcile Linker

# Keep credentials unique
ACCOUNT_UNIQUE_EMAIL = True

# Resolves the deprecation warnings by telling allauth to use email-only logins 
# and what fields are expected during signup.
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*']

ACCOUNT_EMAIL_VERIFICATION = 'optional' # Google accounts are pre-verified

# The magic adapter that forces email matching instead of duplicating
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = "authentication.adapters.MySocialAccountAdapter"

# Configuration parameters for Google OAuth
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

# Where to redirect users after successful login
LOGIN_REDIRECT_URL = '/api/workouts/dashboard/' 
LOGOUT_REDIRECT_URL = '/'

# Django REST Framework global settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
}

# SimpleJWT configuration matrix
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),   # Short lifespan for security
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # Long lifespan for user persistence
    'ROTATE_REFRESH_TOKENS': True,                    # Issue a fresh refresh token when used
    'BLACKLIST_AFTER_ROTATION': True,                 # Prevent reuse of older refresh tokens
    'UPDATE_LAST_LOGIN': True,

    # 🍪 Production Cookie Infrastructure 
    'AUTH_COOKIE': 'refresh_token',                   # Name of the cookie dropped in the browser
    'AUTH_COOKIE_DOMAIN': None,                       # Set to '.yourdomain.com' in actual prod
    'AUTH_COOKIE_SECURE': False,                      # Enforces HTTPS ONLY transmission (False for local dev)
    'AUTH_COOKIE_HTTP_ONLY': True,                    # Blocks JS from reading the token (Stops XSS)
    'AUTH_COOKIE_PATH': '/api/auth/',                 # Cookie is ONLY sent to the auth endpoints
    'AUTH_COOKIE_SAMESITE': 'Lax',                    # Mitigates CSRF attack surfaces
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [
                {
                    "address": "redis://127.0.0.1:6379/0", # Local Redis instance for development; replace with production Redis URL in live deployments
                    "socket_timeout": None,
                 }
            ], 
        },
    },
}
# AWS S3 Settings Configuration
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'eu-north-1')

GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
VERTEX_PROJECT_ID = os.getenv("VERTEX_PROJECT_ID")
VERTEX_LOCATION = os.getenv("VERTEX_LOCATION", "us-central1")
# Explicitly mapping the programmatic authentication file path in the project root
VERTEX_CREDENTIALS_PATH = os.path.join(BASE_DIR, "gcp-vertex-sa.json")

# Brevo API Configurations
BREVO_API_KEY = os.getenv("BREVO_API_KEY")
DEFAULT_FROM_EMAIL = os.getenv("BREVO_SENDER_EMAIL", "hijazeenrakan1@gmail.com")
BREVO_SENDER_NAME = os.getenv("BREVO_SENDER_NAME", "Vertex Fit AI")

# Use our custom API Backend as Django's default email backend
EMAIL_BACKEND = "authentication.email_backend.BrevoAPIBackend"