# Generated by Django 5.0.6 on 2026-06-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
