# Generated by Django 5.0.6 on 2026-07-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workoutsession_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending VLM Processing'), ('completed', 'Analysis Complete'), ('failed', 'Analysis Failed')], default='pending', help_text='Tracks the backend analysis execution state cycle', max_length=15),
        ),
    ]
