# Generated by Django 5.0.6 on 2026-07-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20260703_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='fallback_anchor_joint',
            field=models.IntegerField(blank=True, help_text='Optional fallback node index when the primary anchor is occluded', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='track_horizontally',
            field=models.BooleanField(default=False, help_text='If true, track X-axis motion for rep detection'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='anchor_joint',
            field=models.IntegerField(default=24, help_text='MediaPipe keypoint node index'),
        ),
    ]
