# Generated by Django 5.0.6 on 2026-07-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_exercise_fallback_anchor_joint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='report_language',
            field=models.CharField(default='English', max_length=10),
        ),
    ]
