# Generated by Django 5.0.6 on 2026-07-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_workoutsession_status_chatthread_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
