# Generated by Django 5.0.6 on 2026-07-17 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secure, non-sequential unique identifier for the chat thread.', primary_key=True, serialize=False)),
                ('is_group', models.BooleanField(default=False, help_text='Designates whether this thread is a group chat with multiple users.')),
                ('name', models.CharField(blank=True, help_text='Optional name for the thread, primarily utilized for group chats.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(help_text='Users belonging to this conversation.', related_name='social_direct_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='pending', help_text='The current state of the relationship.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(help_text='The user receiving the friendship request.', on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='The user initiating the friendship request.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['sender', 'receiver', 'status'], name='social_frie_sender__1a102d_idx')],
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The content of the message.')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the message has been read by the recipient.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(help_text='The user who sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(help_text='The parent thread context of this message.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.thread')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread', 'created_at'], name='social_mess_thread__9cbc0a_idx')],
            },
        ),
    ]
